# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'CircularPickerViewSwift' do
pod 'CircularPickerView', :git => 'https://github.com/alexey-kubas-appus/Circular-PickerView'

end